# Generated by Django 5.0.6 on 2024-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelorder',
            old_name='order_transaction_id',
            new_name='order_number',
        ),
    ]
