# Generated by Django 5.0.6 on 2024-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_order_transaction_id_modelorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='cart_image',
            field=models.ImageField(default=1, upload_to='Cart_File_Photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='product_image',
            field=models.ImageField(upload_to='products_File_Photo/'),
        ),
    ]
