# Generated by Django 5.0.6 on 2024-05-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='ModelCoupon',
        ),
    ]
